# Production docker-compose configuration
# Run with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  backend:
    # Remove development volumes and overrides
    volumes: []
    environment:
      # Production environment variables
      - PYTHONUNBUFFERED=1
      - UVICORN_WORKERS=4
    command: ["python", "-m", "uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    # Remove development volumes
    volumes: []
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: crossword-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - crossword-network